import type { Dataset } from "./types"

export const mockGrammarDataset: Dataset = {
  id: "mock-grammar-1",
  fileName: "grammar_n5_basic.json",
  createdAt: new Date().toISOString(),
  type: 1,
  totalQuestions: 10,
  questions: [
    {
      id: "g1",
      type: 1,
      question: "私は日本語を＿＿＿います。",
      answers: ["勉強して", "勉強する", "勉強した", "勉強"],
      correct: "勉強して",
      explain: "「〜ています」は現在進行形や習慣を表します。「勉強しています」= I am studying / I study",
      played: false,
    },
    {
      id: "g2",
      type: 1,
      question: "明日、友達＿＿＿会います。",
      answers: ["を", "に", "で", "が"],
      correct: "に",
      explain: "「〜に会う」で「meet someone」の意味になります。",
      played: false,
    },
    {
      id: "g3",
      type: 1,
      question: "この本は＿＿＿ですか。",
      answers: ["だれの", "なにの", "どこの", "いつの"],
      correct: "だれの",
      explain: "「だれの」は「whose」の意味で、所有者を聞く疑問詞です。",
      played: false,
    },
    {
      id: "g4",
      type: 1,
      question: "電車＿＿＿学校へ行きます。",
      answers: ["を", "に", "で", "が"],
      correct: "で",
      explain: "「〜で」は手段・方法を表す助詞です。「電車で」= by train",
      played: false,
    },
    {
      id: "g5",
      type: 1,
      question: "日本語は英語＿＿＿難しいです。",
      answers: ["から", "より", "まで", "ほど"],
      correct: "より",
      explain: "「AはBより〜」で比較を表します。「より」= than",
      played: false,
    },
    {
      id: "g6",
      type: 1,
      question: "映画を見＿＿＿、ご飯を食べました。",
      answers: ["てから", "ながら", "ても", "たり"],
      correct: "てから",
      explain: "「〜てから」は「after doing ~」の意味です。",
      played: false,
    },
    {
      id: "g7",
      type: 1,
      question: "この料理は＿＿＿作れますか。",
      answers: ["どう", "どうやって", "どこ", "いつ"],
      correct: "どうやって",
      explain: "「どうやって」は「how to / in what way」の意味です。",
      played: false,
    },
    {
      id: "g8",
      type: 1,
      question: "雨が降って＿＿＿、試合は中止になりました。",
      answers: ["ので", "から", "たら", "ても"],
      correct: "ので",
      explain: "「〜ので」は理由を表す丁寧な表現です。",
      played: false,
    },
    {
      id: "g9",
      type: 1,
      question: "食べ＿＿＿ください。",
      answers: ["て", "た", "る", "ます"],
      correct: "て",
      explain: "「〜てください」は丁寧な依頼・お願いの表現です。",
      played: false,
    },
    {
      id: "g10",
      type: 1,
      question: "彼女は歌を歌う＿＿＿が上手です。",
      answers: ["こと", "もの", "ところ", "はず"],
      correct: "こと",
      explain: "「〜ことが上手」で「be good at ~ing」の意味になります。",
      played: false,
    },
  ],
}

export const mockVocabularyDataset: Dataset = {
  id: "mock-vocab-1",
  fileName: "vocabulary_n5_basic.json",
  createdAt: new Date().toISOString(),
  type: 2,
  totalQuestions: 10,
  questions: [
    {
      id: "v1",
      type: 2,
      question: "「りんご」の意味は何ですか。",
      answers: ["Apple", "Orange", "Banana", "Grape"],
      correct: "Apple",
      explain: "りんご = Apple（リンゴ）",
      played: false,
    },
    {
      id: "v2",
      type: 2,
      question: "「学校」の読み方は何ですか。",
      answers: ["がっこう", "がくこう", "かっこう", "かくこう"],
      correct: "がっこう",
      explain: "学校（がっこう）= school",
      played: false,
    },
    {
      id: "v3",
      type: 2,
      question: "「食べる」の意味は何ですか。",
      answers: ["To eat", "To drink", "To sleep", "To walk"],
      correct: "To eat",
      explain: "食べる（たべる）= to eat",
      played: false,
    },
    {
      id: "v4",
      type: 2,
      question: "「先生」の読み方は何ですか。",
      answers: ["せんせい", "せいせん", "さんせい", "しんせい"],
      correct: "せんせい",
      explain: "先生（せんせい）= teacher",
      played: false,
    },
    {
      id: "v5",
      type: 2,
      question: "「大きい」の反対語は何ですか。",
      answers: ["小さい", "長い", "短い", "高い"],
      correct: "小さい",
      explain: "大きい（おおきい）の反対は小さい（ちいさい）= small",
      played: false,
    },
    {
      id: "v6",
      type: 2,
      question: "「水」の読み方は何ですか。",
      answers: ["みず", "すい", "みす", "ひ"],
      correct: "みず",
      explain: "水（みず）= water",
      played: false,
    },
    {
      id: "v7",
      type: 2,
      question: "「電話」の意味は何ですか。",
      answers: ["Telephone", "Television", "Computer", "Radio"],
      correct: "Telephone",
      explain: "電話（でんわ）= telephone / phone",
      played: false,
    },
    {
      id: "v8",
      type: 2,
      question: "「今日」の読み方は何ですか。",
      answers: ["きょう", "こんにち", "きんび", "けふ"],
      correct: "きょう",
      explain: "今日（きょう）= today",
      played: false,
    },
    {
      id: "v9",
      type: 2,
      question: "「美しい」の意味は何ですか。",
      answers: ["Beautiful", "Ugly", "Fast", "Slow"],
      correct: "Beautiful",
      explain: "美しい（うつくしい）= beautiful",
      played: false,
    },
    {
      id: "v10",
      type: 2,
      question: "「朝ご飯」の意味は何ですか。",
      answers: ["Breakfast", "Lunch", "Dinner", "Snack"],
      correct: "Breakfast",
      explain: "朝ご飯（あさごはん）= breakfast",
      played: false,
    },
  ],
}

export const mockMixedDataset: Dataset = {
  id: "mock-mixed-1",
  fileName: "mixed_practice.json",
  createdAt: new Date().toISOString(),
  type: 1,
  totalQuestions: 6,
  questions: [
    {
      id: "m1",
      type: 1,
      question: "彼は毎日＿＿＿に起きます。",
      answers: ["六時", "六時間", "六日", "六つ"],
      correct: "六時",
      explain: "「〜時に」で時刻を表します。六時（ろくじ）= 6 o'clock",
      played: false,
    },
    {
      id: "m2",
      type: 2,
      question: "「猫」の読み方は何ですか。",
      answers: ["ねこ", "いぬ", "とり", "さかな"],
      correct: "ねこ",
      explain: "猫（ねこ）= cat",
      played: false,
    },
    {
      id: "m3",
      type: 1,
      question: "この映画は面白い＿＿＿思います。",
      answers: ["と", "を", "に", "が"],
      correct: "と",
      explain: "「〜と思う」で意見や考えを表します。",
      played: false,
    },
    {
      id: "m4",
      type: 2,
      question: "「駅」の意味は何ですか。",
      answers: ["Station", "Store", "Hospital", "School"],
      correct: "Station",
      explain: "駅（えき）= station",
      played: false,
    },
    {
      id: "m5",
      type: 1,
      question: "日本へ＿＿＿ことがありますか。",
      answers: ["行った", "行く", "行って", "行き"],
      correct: "行った",
      explain: "「〜たことがある」で経験を表します。",
      played: false,
    },
    {
      id: "m6",
      type: 2,
      question: "「嬉しい」の意味は何ですか。",
      answers: ["Happy", "Sad", "Angry", "Tired"],
      correct: "Happy",
      explain: "嬉しい（うれしい）= happy / glad",
      played: false,
    },
  ],
}

export const allMockDatasets = [mockGrammarDataset, mockVocabularyDataset, mockMixedDataset]
